-- MySQL Script generated by MySQL Workbench
-- Tue Dec  1 16:31:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProyMD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProyMD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyMD` DEFAULT CHARACTER SET utf8 ;
USE `ProyMD` ;

-- -----------------------------------------------------
-- Table `ProyMD`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyMD`.`Login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(200) NOT NULL,
  `pass` VARCHAR(200) NOT NULL,
  `correo` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idLogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyMD`.`Areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyMD`.`Areas` (
  `idArea` INT NOT NULL AUTO_INCREMENT,
  `nomArea` VARCHAR(200) NOT NULL,
  `descripcionArea` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idArea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyMD`.`Puestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyMD`.`Puestos` (
  `idPuesto` INT NOT NULL AUTO_INCREMENT,
  `nomPuesto` VARCHAR(200) NOT NULL,
  `descripcionPuesto` VARCHAR(200) NOT NULL,
  `fk_idArea` INT NOT NULL,
  PRIMARY KEY (`idPuesto`, `fk_idArea`),
  INDEX `fk_Puestos_Areas1_idx` (`fk_idArea` ASC),
  CONSTRAINT `fk_Puestos_Areas1`
    FOREIGN KEY (`fk_idArea`)
    REFERENCES `ProyMD`.`Areas` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyMD`.`DatosPersonales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyMD`.`DatosPersonales` (
  `idDatoPersonal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `app` VARCHAR(200) NOT NULL,
  `apm` VARCHAR(200) NOT NULL,
  `edad` INT NOT NULL,
  `fk_idLogin` INT NOT NULL,
  `fk_idPuesto` INT NOT NULL,
  PRIMARY KEY (`idDatoPersonal`, `fk_idLogin`, `fk_idPuesto`),
  INDEX `fk_DatosPersonales_Login_idx` (`fk_idLogin` ASC),
  INDEX `fk_DatosPersonales_Puestos1_idx` (`fk_idPuesto` ASC),
  CONSTRAINT `fk_DatosPersonales_Login`
    FOREIGN KEY (`fk_idLogin`)
    REFERENCES `ProyMD`.`Login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DatosPersonales_Puestos1`
    FOREIGN KEY (`fk_idPuesto`)
    REFERENCES `ProyMD`.`Puestos` (`idPuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
